name: CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install deps
      run: sudo apt-get update -qq && sudo apt-get install -qq cppcheck gcc-avr binutils-avr avr-libc zip
    - uses: actions/checkout@v3
    - name: make
      run: make all
    - name: make check
      run: make check
